runtime: nodejs16
env: standard
service: frontend

automatic_scaling:
  min_instances: 1
  max_instances: 1

instance_class: F1

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
